### ISSUE TITLE
Support for IAM roles

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/docker-compose-aws-ecscli-demo#48]
**Is your feature request related to a problem? Please describe.**
When using IAM roles:
- By default to get details about an IAM role the timeout and retry are defined by `AWS_METADATA_SERVICE_TIMEOUT` and `AWS_METADATA_SERVICE_NUM_ATTEMPTS`. In some with large number of ecs container being created these parameters need to be tweaked. 
- When launching stream loader, an additional parameter is needed(`--task-role-arn`) to pass the IAM role to the ecs container. Currently we are able to work around this by adding it to the command this way
```
ecs-cli compose \ 
--cluster-config ${SENZING_AWS_ECS_CLUSTER_CONFIG} \ 
--ecs-params ${GIT_REPOSITORY_DIR}/resources/advanced-10M/ecs-params-stream-loader.yaml \ 
--file ${GIT_REPOSITORY_DIR}/resources/advanced-10M/docker-compose-stream-loader.yaml \ 
--project-name ${SENZING_AWS_PROJECT}-project-name-stream-loader \ 
--task-role-arn arn:aws:iam::<accountId>:role/ecsTaskExecutionRole service up
```

**Describe the solution you'd like**
- In the `docker-compose-stream-loader.yaml` please add support to read `AWS_METADATA_SERVICE_TIMEOUT` and `AWS_METADATA_SERVICE_NUM_ATTEMPTS` from environment variables similar to `AWS_DEFAULT_REGION`

- In the `ecs-params-stream-loader.yaml` please add support to set `task_role_arn` with value defaulted to`ecsTaskExecutionRole` or update the documentation to indicate this.

**Comment by docktermj** [comment]
I'm not sure I can pull this off.  I added the following lines:

https://github.com/Senzing/docker-compose-aws-ecscli-demo/blob/99f46000408de688bc81e67dbac018593bd45d64/resources/advanced/docker-compose-stream-producer-1.yaml#L7-L8

And then saw this in the log:

```console

2021-02-17 15:37:55,175 senzing-50140297I Enter {     "debug": false,     "default_data_source": null,     "default_entity_type": null,     "delay_in_seconds": 0,     "input_counter": 0,     "input_url": "https://public-read-access.s3.amazonaws.com/TestDataSets/test-dataset-100m.json.gz",     "kafka_bootstrap_server": "localhost:9092",     "kafka_poll_interval": 100,     "kafka_topic": "senzing-kafka-topic",     "monitoring_period_in_seconds": 60,     "output_counter": 0,     "output_counter_reported": 0,     "program_updated": "2020-10-09",     "program_version": "1.2.3",     "rabbitmq_exchange": "senzing-rabbitmq-exchange",     "rabbitmq_host": "localhost",     "rabbitmq_password": "bitnami",     "rabbitmq_port": "5672",     "rabbitmq_queue": "senzing-rabbitmq-queue",     "rabbitmq_routing_key": "senzing.records",     "rabbitmq_use_existing_entities": false,     "rabbitmq_username": "user",     "read_queue_maxsize": 200,     "record_identifier": "RECORD_ID",     "record_max": 5000000,     "record_min": 1,     "record_monitor": 100000,     "record_size_max": 0,     "sleep_time_in_seconds": 0,     "sqs_delay_seconds": 0,     "sqs_queue_url": "https://sqs.us-east-1.amazonaws.com/488776654093/mjd-01-sqs-queue",     "start_time": 1613576275.1752539,     "subcommand": "gzipped-json-to-sqs-batch",     "threads_per_print": 30 }
--
2021-02-17 15:37:55,178 senzing-50140129I Process-0-FilterUrlGzippedJsonToDictQueueThread-0 is running.
Traceback (most recent call last):
File "/app/stream-producer.py", line 2352, in <module>
globals()[subcommand_function_name](args)
File "/app/stream-producer.py", line 2172, in do_gzipped_json_to_sqs_batch
dohelper_gzipped_json(args, write_thread)
File "/app/stream-producer.py", line 1998, in dohelper_gzipped_json
governor=governor
File "/app/stream-producer.py", line 1863, in pipeline_read_write
governor=governor
File "/app/stream-producer.py", line 1662, in __init__
base.__init__(self, *args, **kwargs)
File "/app/stream-producer.py", line 1461, in __init__
self.sqs = boto3.client("sqs")
File "/usr/local/lib/python3.7/dist-packages/boto3/__init__.py", line 91, in client
return _get_default_session().client(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/boto3/session.py", line 263, in client
aws_session_token=aws_session_token, config=config)
File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 823, in create_client
credentials = self.get_credentials()
File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 428, in get_credentials
'credential_provider').load_credentials()
File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 919, in get_component
self._components[name] = factory()
File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 149, in _create_credential_resolver
self, region_name=self._last_client_region_used
File "/usr/local/lib/python3.7/dist-packages/botocore/credentials.py", line 64, in create_credential_resolver
metadata_timeout = session.get_config_variable('metadata_service_timeout')
File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 238, in get_config_variable
logical_name)
File "/usr/local/lib/python3.7/dist-packages/botocore/configprovider.py", line 293, in get_config_variable
return provider.provide()
File "/usr/local/lib/python3.7/dist-packages/botocore/configprovider.py", line 392, in provide
return self._convert_type(value)
File "/usr/local/lib/python3.7/dist-packages/botocore/configprovider.py", line 397, in _convert_type
return self._conversion_func(value)
ValueError: invalid literal for int() with base 10: ''
2021-02-17 15:49:13,091 senzing-50140298I Exit Namespace(subcommand='gzipped-json-to-sqs-batch')
```

**Comment by docktermj** [comment]
Maybe I can put in default values.

```yaml
      AWS_METADATA_SERVICE_NUM_ATTEMPTS: ${AWS_METADATA_SERVICE_NUM_ATTEMPTS:-1}
      AWS_METADATA_SERVICE_TIMEOUT: ${AWS_METADATA_SERVICE_TIMEOUT:-1}
```

**Comment by docktermj** [comment]
@ssasidharanwp,  I've made the following changes in the master branch:  https://github.com/Senzing/docker-compose-aws-ecscli-demo/pull/50.  Does that fulfill your request?

**Comment by docktermj** [comment]
@ssasidharanwp Let me know if your issue has been addressed.  If we don't hear back in 7 days, we'll go ahead and close the issue.

**Comment by docktermj** [comment]
Closing the issue. Feel free to reopen or create a new issue.
